Vagrant.configure("2") do |config|
	config.vm.provider :virtualbox do |mariadb01|
		mariadb01.customize ["modifyvm", :id, "--memory", 1024]
	end
	config.vm.define "mariadb-01" do |mariadb01|
		mariadb01.vm.box = "debian/buster64"
		mariadb01.vm.hostname = "mariadb-01"
		mariadb01.vm.network "private_network", ip: "10.100.0.81"
    mariadb01.vm.synced_folder ".", "/vagrant_data", disabled: true
		mariadb01.vm.provision "shell" do |sh|
			sh.inline = <<-SHELL
				sudo sed -i 's/#ListenAddress 0.0.0.0/ListenAddress 0.0.0.0/g' /etc/ssh/sshd_config
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        echo "" > /home/vagrant/.ssh/authorized_keys
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDUaFMXIfnRnXSMEl37rw6l5GMsDHq9R/QdA7G+pr81/llTgOD/VpE1ZHGnAaPWv8zwrOJU9VT5Tw90Y3FrbacmpVdqZRR74Lqg48htmwVD9GOgXD7+eTpRSCPkoNVdVtjbIXjebkBlRw7GVBfQLYn+t8uX2LR4apGs1EZ1sjQ9Broho3bXXkejQ2K17SBieAUtTIcv3jySH5Q7wmzA4O2o8a55uxf1dVHsWnZ8slYG/hmbxfKD1zANt60UXaRxhN5wNIqBn8A5aPxybjl7Qo7UZSsgWivoPXA9w/jWMH7xKqjmdvTi8b+0sedxvdJtGh5ncmNigKPAVwsCmHDENUkWPghUVjpjdwesOtngc+LNTDrhUOkGEovEccJx3vdEojsh2BS41Kt92M9k2Oz9LmScxy3oZ6ImRvbTxBpEqWFesh6YiejtMy16+CcC2ISVhWDJjx6O9LukZ3xJ7eUHET5vfEhL0rrappg0ksMoHThLDLaA+9EIfRLZH9gQ1LEw1ojQlQM0TVJJZ9upUKwz0Nu1wnTXQHGxnqUuhdAoWH5e7PiTMHkiLqQpFrM12uKEdrxt6bvhRpk4Ptc0NZ9qJCry2sA5Snhv25lDRsQpODmE3tDG3zzA9tgSxHVWgxAp0IYVjuas5gJlnsc9xugcaAicG+8UDjgcvd5TD5zSbr9Z8Q== vagrant" >> /home/vagrant/.ssh/authorized_keys
				sudo systemctl restart sshd
			SHELL
		end
	end
	
	config.vm.provider :virtualbox do |mariadb02|
		mariadb02.customize ["modifyvm", :id, "--memory", 1024]
	end
	config.vm.define "mariadb-02" do |mariadb02|
		mariadb02.vm.box = "debian/buster64"
		mariadb02.vm.hostname = "mariadb-02"
		mariadb02.vm.network "private_network", ip: "10.100.0.82"
    mariadb02.vm.synced_folder ".", "/vagrant_data", disabled: true
		mariadb02.vm.provision "shell" do |sh|
			sh.inline = <<-SHELL
				sudo sed -i 's/#ListenAddress 0.0.0.0/ListenAddress 0.0.0.0/g' /etc/ssh/sshd_config
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        echo "" > /home/vagrant/.ssh/authorized_keys
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDUaFMXIfnRnXSMEl37rw6l5GMsDHq9R/QdA7G+pr81/llTgOD/VpE1ZHGnAaPWv8zwrOJU9VT5Tw90Y3FrbacmpVdqZRR74Lqg48htmwVD9GOgXD7+eTpRSCPkoNVdVtjbIXjebkBlRw7GVBfQLYn+t8uX2LR4apGs1EZ1sjQ9Broho3bXXkejQ2K17SBieAUtTIcv3jySH5Q7wmzA4O2o8a55uxf1dVHsWnZ8slYG/hmbxfKD1zANt60UXaRxhN5wNIqBn8A5aPxybjl7Qo7UZSsgWivoPXA9w/jWMH7xKqjmdvTi8b+0sedxvdJtGh5ncmNigKPAVwsCmHDENUkWPghUVjpjdwesOtngc+LNTDrhUOkGEovEccJx3vdEojsh2BS41Kt92M9k2Oz9LmScxy3oZ6ImRvbTxBpEqWFesh6YiejtMy16+CcC2ISVhWDJjx6O9LukZ3xJ7eUHET5vfEhL0rrappg0ksMoHThLDLaA+9EIfRLZH9gQ1LEw1ojQlQM0TVJJZ9upUKwz0Nu1wnTXQHGxnqUuhdAoWH5e7PiTMHkiLqQpFrM12uKEdrxt6bvhRpk4Ptc0NZ9qJCry2sA5Snhv25lDRsQpODmE3tDG3zzA9tgSxHVWgxAp0IYVjuas5gJlnsc9xugcaAicG+8UDjgcvd5TD5zSbr9Z8Q== vagrant" >> /home/vagrant/.ssh/authorized_keys
				sudo systemctl restart sshd
			SHELL
		end
	end
	
	config.vm.provider :virtualbox do |mariadb03|
		mariadb03.customize ["modifyvm", :id, "--memory", 1024]
	end
    config.vm.define "mariadb-03" do |mariadb03|
		mariadb03.vm.box = "debian/buster64"
		mariadb03.vm.hostname = "mariadb-03"
		mariadb03.vm.network "private_network", ip: "10.100.0.83"
    mariadb03.vm.synced_folder ".", "/vagrant_data", disabled: true
		mariadb03.vm.provision "shell" do |sh|
			sh.inline = <<-SHELL
				sudo sed -i 's/#ListenAddress 0.0.0.0/ListenAddress 0.0.0.0/g' /etc/ssh/sshd_config
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        echo "" > /home/vagrant/.ssh/authorized_keys
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDUaFMXIfnRnXSMEl37rw6l5GMsDHq9R/QdA7G+pr81/llTgOD/VpE1ZHGnAaPWv8zwrOJU9VT5Tw90Y3FrbacmpVdqZRR74Lqg48htmwVD9GOgXD7+eTpRSCPkoNVdVtjbIXjebkBlRw7GVBfQLYn+t8uX2LR4apGs1EZ1sjQ9Broho3bXXkejQ2K17SBieAUtTIcv3jySH5Q7wmzA4O2o8a55uxf1dVHsWnZ8slYG/hmbxfKD1zANt60UXaRxhN5wNIqBn8A5aPxybjl7Qo7UZSsgWivoPXA9w/jWMH7xKqjmdvTi8b+0sedxvdJtGh5ncmNigKPAVwsCmHDENUkWPghUVjpjdwesOtngc+LNTDrhUOkGEovEccJx3vdEojsh2BS41Kt92M9k2Oz9LmScxy3oZ6ImRvbTxBpEqWFesh6YiejtMy16+CcC2ISVhWDJjx6O9LukZ3xJ7eUHET5vfEhL0rrappg0ksMoHThLDLaA+9EIfRLZH9gQ1LEw1ojQlQM0TVJJZ9upUKwz0Nu1wnTXQHGxnqUuhdAoWH5e7PiTMHkiLqQpFrM12uKEdrxt6bvhRpk4Ptc0NZ9qJCry2sA5Snhv25lDRsQpODmE3tDG3zzA9tgSxHVWgxAp0IYVjuas5gJlnsc9xugcaAicG+8UDjgcvd5TD5zSbr9Z8Q== vagrant" >> /home/vagrant/.ssh/authorized_keys
				sudo systemctl restart sshd
			SHELL
		end
	end
end