Vagrant.configure("2") do |config|

	config.vm.define "kubemaster" do |kubemaster|
		kubemaster.vm.box = "generic/debian12"
		kubemaster.vm.hostname = "kubemaster"
		kubemaster.vm.network "private_network", ip: "192.168.56.11"
        kubemaster.vm.provision "docker"
		kubemaster.vm.provision "shell" do |sh|
			sh.inline = <<-SHELL
				sudo sed -i 's/#ListenAddress 0.0.0.0/ListenAddress 0.0.0.0/g' /etc/ssh/sshd_config
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        echo "" > /home/vagrant/.ssh/authorized_keys
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDDzTprd+XCZkXwxQxU6Gc49SZS/R0PCXdP443HSJcLSpS65kvigneZ48hmgEsHxmGEe1QrzzIoNHdUsOJbHyPcKYLT/ZpkzizqTPVctCMCtjZoZoi7VYvYG12enoVKy6T8RUkuObu1CdTxjtzXD71QAh9ZlAiWXcEbYOY2bjjGQ9WmtGGrbQg2s89DxIYUzjgwEexggJaRZf/pfO3RS8aHfyhnSezwCnQDHD2w3hZAJjlGo2qVgAo/9pMJLkQ55wQBEpvidgUjoA6fjX+JTplQcZ5kqBMNcyPSHhZiLgmOdYAOk+xPYtpl4Vz5uK6kAgm/5XcXY4tMKzR42fwxOCYzWFu43sVf05ZkZCjZhvnPDkSWL1utAetbXMW6T308+6MKXwBITGS8+BxVHDR7yxcoqMZMhT5DVrXbpsF8Qhiu5mVFsjYC6Q3TJyLffNaIhS+dukMWTLb+vRzMuHapAHAG7vFkthsFYClS6h/THUA/EIyn/JKR4KnYyWGHF+fMcKy45Ub2JOUOnEUkxmmhwPAMWZxxgft5TM+5X20xRATtO7zInkwEkngmLVw4+QT1KNteBNpER6wQzMZ9IqzcJVy427y+5fQIZ5Hr+ryPI45A1qC3N86U//lljPiHtSPGL4ocxhxc4764foxTPj41gS1jFzJkietJAmuYq9IqKPRQuw== alexandre.nguyen@deveryware.com" >> /home/vagrant/.ssh/authorized_keys
				sudo systemctl restart sshd
			SHELL
		end
        kubemaster.vm.provider :virtualbox do |v|
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--memory", "2048"]
            v.customize ["modifyvm", :id, "--cpus", "2"]
            v.customize ["modifyvm", :id, "--name", "kubemaster"]            
        end
	end

	config.vm.define "kubenode" do |kubenode|
		kubenode.vm.box = "generic/debian12"
		kubenode.vm.hostname = "kubenode"
		kubenode.vm.network "private_network", ip: "192.168.56.12"
        kubenode.vm.provision "docker"
		kubenode.vm.provision "shell" do |sh|
			sh.inline = <<-SHELL
				sudo sed -i 's/#ListenAddress 0.0.0.0/ListenAddress 0.0.0.0/g' /etc/ssh/sshd_config
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        echo "" > /home/vagrant/.ssh/authorized_keys
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDDzTprd+XCZkXwxQxU6Gc49SZS/R0PCXdP443HSJcLSpS65kvigneZ48hmgEsHxmGEe1QrzzIoNHdUsOJbHyPcKYLT/ZpkzizqTPVctCMCtjZoZoi7VYvYG12enoVKy6T8RUkuObu1CdTxjtzXD71QAh9ZlAiWXcEbYOY2bjjGQ9WmtGGrbQg2s89DxIYUzjgwEexggJaRZf/pfO3RS8aHfyhnSezwCnQDHD2w3hZAJjlGo2qVgAo/9pMJLkQ55wQBEpvidgUjoA6fjX+JTplQcZ5kqBMNcyPSHhZiLgmOdYAOk+xPYtpl4Vz5uK6kAgm/5XcXY4tMKzR42fwxOCYzWFu43sVf05ZkZCjZhvnPDkSWL1utAetbXMW6T308+6MKXwBITGS8+BxVHDR7yxcoqMZMhT5DVrXbpsF8Qhiu5mVFsjYC6Q3TJyLffNaIhS+dukMWTLb+vRzMuHapAHAG7vFkthsFYClS6h/THUA/EIyn/JKR4KnYyWGHF+fMcKy45Ub2JOUOnEUkxmmhwPAMWZxxgft5TM+5X20xRATtO7zInkwEkngmLVw4+QT1KNteBNpER6wQzMZ9IqzcJVy427y+5fQIZ5Hr+ryPI45A1qC3N86U//lljPiHtSPGL4ocxhxc4764foxTPj41gS1jFzJkietJAmuYq9IqKPRQuw== alexandre.nguyen@deveryware.com" >> /home/vagrant/.ssh/authorized_keys
				sudo systemctl restart sshd
			SHELL
		end
        kubenode.vm.provider :virtualbox do |v|
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--memory", "2048"]
            v.customize ["modifyvm", :id, "--cpus", "2"]
            v.customize ["modifyvm", :id, "--name", "kubenode"]            
        end
	end
end